### ISSUE TITLE
[Forge] [1.20.1] Igniting modded explosives with fire lighter items spawns vanilla primed TNT instead (Formidibomb from CWSM, Nova Cata items from ProjectE)

### ISSUE THREAD

**Issue by pinkygrocket** [LieOnLion/Quad#13] opened 2024-10-19 04:59 UTC
If both Quad and [Cracker's Wither Storm Mod](https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod) are installed, manually lighting a Formidibomb (essentially a magic nuke) with Flint and Steel spawns primed vanilla TNT, instead of spawning the primed Formidibomb. This forces the player to wait out the Formidibomb's inventory fuse time.

https://mclo.gs/IhZkl9h

[Issue on CWSM issue tracker](https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/2244)

**Comment by lieonlion** [comment] 2024-10-19 05:56
I am unsure if I am able to fix this due to the mod being closed source, so I don't know how Quad is affecting it as I can't see how it works.

**Comment by Billnotic** [comment] 2024-10-20 17:05
Also having this issue, shame it'd be difficult to fix.

**Comment by etmoonshade** [comment] 2024-11-07 19:33
This also happens with ProjectE's Nova Cata* items - just spent a while removing mods to find this out.

I'll link this over to https://github.com/sinkillerj/ProjectE/issues/2369 which has a video showing the issue. Hopefully working with an open source mod will help you dig up the solution.

Versions:
Quad 1.2.5 + 1.20.4
Minecraft 1.20.1
ProjectE-1.20.1-PE1.0.1
Forge 47.3.0

**Comment by etmoonshade** [comment] 2024-11-07 19:35
If it's helpful, here's the Discord chatter we had about this:

> [12:08 PM]pupnewfster: guessing one of your other mods is somehow modifying "tnt"
[12:09 PM]Epsilon: Now I'm curious. I'll have to play with it.
[12:09 PM]pupnewfster: and just entirely replacing it
[12:09 PM]pupnewfster: rather than only replacing vanilla tnt
[12:09 PM]Epsilon: Also, that boom is more painful and less big than I remembered. :P
[12:12 PM]Epsilon: Dropped a comment on the issue. I'll see what I can do to narrow it down and let y'all determine if there's a sane way to fix it.
[12:14 PM]pupnewfster: my guess is some mod is doing an instanceof check instead of an class equality check, and they will have to be the ones to fix it on their end

(edit: To be clear, pupnewfster is one of the ProjectE devs - this is at least an informed guess considering there was no other context when we had this conversation)

**Comment by pinkygrocket** [comment] 2024-11-07 21:30
Though this issue involves two seperate mods, since the issues are essentially identical, I've updated the title to reflect that this also affects ProjectE

**Comment by etmoonshade** [comment] 2024-11-07 21:43
I played a bit more with this. First, I reproduced the issue with a Thermal explosive as well (though not in a clean install - note that the issue HAS been reproduced in a clean install with only ProjectE, JEI, and Quad.)

I also found that igniting things with a redstone torch DOES make the explosive work as expected - no sprite change, and the explosion is as large as it should be. Hopefully that helps y'all track down what's happening.

**Comment by lieonlion** [comment] 2024-11-12 21:25
@pinkygrocket @Billnotic @etmoonshade I have found the issue, it is due to me calling the `explode()` function when lighting the tnt, however forge decided to make it just set the block on fire, which calls the `wasExploded()` function in the tnt class, which these mods seem to override the `wasExploded()` function but not `explode()`. A fix will be released in 24-48 hours.

**Comment by Billnotic** [comment] 2024-11-13 17:23
Sick, thanks for fixing it.

**Comment by lieonlion** [comment] 2024-11-13 21:24
Fixed with version 1.2.9.

[CurseForge](https://www.curseforge.com/minecraft/mc-mods/quad/files/5900857)
[Modrinth](https://modrinth.com/mod/quad/version/1.2.9+1.20.4-Forge)

**Closed as completed by lieonlion** 2024-11-13 21:24 UTC
